#!/usr/bin/env bash
# install nginx server, redirects /redirect_me. a customizes 404 not found
apt-get -y update
apt-get -y install nginx
echo 'Hello World!' > /var/www/html/index.html
echo "Ceci n'est pas une page" > /usr/share/nginx/html/custom_404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/youtu.be\/dQw4w9WgXcQ permanent;/" /etc/nginx/sites-available/default
service nginx start
