#!/usr/bin/env bash
# displays the content of the file /etc/passwd
while IFS=":" read -r a b c d e f g
do
  echo "The user $a is part of the $d gang, lives in $f and rides $g. $c's place is protected by the passcode $b, more info about the user here: $e"
done <<< "$(cat /etc/passwd)"
