#!/usr/bin/env bash
# print "Best School" 10 times to stdout but for the 9th iteration, display Hi
i=1
while [ $i -le 10 ]
do
    echo "Best School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    ((i++))
done
