#!/usr/bin/env bash
# print "Best School" 10 times to stdout but for the 9th iteration, display Hi
i=0
while [[ $i -ne 10 ]];
do
	i=$(( i + 1 ))
	if [[ $i == 9 ]];then
		echo "Hi"
	else
		echo "Best School"
	fi
done
