#!/usr/bin/env bash
i=0
while [[ $i -ne 20 ]];
do
	i=$(($i + 1))
	case $i in
		4)
			echo "bad luck from China" ;;
		9)
			echo "bad luck from Japan" ;;
		17)
			echo "bad luck from Italy" ;;
		*)
			echo "$i" ;;
	esac
done
