#!/usr/bin/env bash
# nested if statement
if [[ -a './school' ]] && [[ ! -s './school' ]];
then
	echo -e "school file exists\nschool file is empty"
elif [[ -s './school' ]]; then
	echo -e "school file exists\nschool file is not empty"
else
	echo "school file does not exist"
fi

if [[ -f './school' ]];then
	echo "school file is a regular file"
fi
